### ISSUE TITLE
Lawma-8b and Lawma-70B huggingface model missing tokenizer

### ISSUE THREAD

**Issue by Yixing-Li** [socialfoundations/lawma#1]
Thanks for your work. But there seems some file missing:

1.  Seems missing Tokenizer on huggingface, https://huggingface.co/ricdomolm/lawma-8b
2.  Please explain the package used in evaluation hf_eval.py
` from llm_utils import  load_tokenizer_model, etc `
There seems no .py named llm_utils and llm_utils package seems don't have load_tokenizer_model function
`pip install llm_utils `
![image](https://github.com/user-attachments/assets/f7333135-bd15-4c26-a64a-2bd256dab2cc)

**Comment by Yixing-Li** [comment]
Not a big deal with this problem. I've got tokenizer from the official llama3-8b-instruction huggingface.
But probably you could add tokenizer to your huggingface :)

**Comment by RicardoDominguez** [comment]
Thanks! Just added the tokenizer. I'm also adding the `llm_utils` file now.
