### ISSUE TITLE
Caselaw Project metadata not available in data_generation / download_sc_data.py

### ISSUE THREAD

**Issue by Yixing-Li** [socialfoundations/lawma#2]
There might be a problem in the data prepare stage. The _Caselaw Project metadata from the caselaw us bulk export_ is not available anymore. 

https://case.law/download/bulk_exports/20200604/by_jurisdiction/case_metadata/us/

https://github.com/socialfoundations/lawma/blob/17801202f148241df38d0e07524b00c6f03495f5/data_generation/download_sc_data.py#L25

**Comment by RicardoDominguez** [comment]
Hi, it seems like the Caselaw Project is undergoing changes and the files are not there anymore. I'll re-upload them if I cannot find the new links.

**Comment by Yixing-Li** [comment]
Thank you for your attention :)

**Comment by RicardoDominguez** [comment]
The code now uses the new [static caselaw site](https://static.case.law/) instead of the depreciated API
